language: node_js

node_js:
  - 10

cache: npm

script:
  - sh .travis/backend_install_dev.sh || travis_terminate 1;
  - sh .travis/backend_tests_and_lint.sh || travis_terminate 1;

after_success:
  - sh .travis/backend_deploy_dockerhub.sh || travis_terminate 1;
  - test “$TRAVIS_BRANCH” = “master” && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/backend_deploy_heroku.sh;


