language: node_js
node_js:
  - 10
script:
  - bash .travis/backend_install_dev.sh || travis_terminate 1;
  - bash .travis/backend_tests_and_lint.sh || travis_terminate 1;
after_success:
  - (test “$TRAVIS_BRANCH” = “master” || test “$TRAVIS_BRANCH” = “Backend”) && bash .travis/backend_deploy.sh;
