language: node_js
node_js:
  - 10
cache:
  directories:
  - docker_images

before_install:
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
script:
  - sh .travis/backend_install_dev.sh || travis_terminate 1;
  - sh .travis/backend_tests_and_lint.sh || travis_terminate 1;
after_success:
  - sh .travis/backend_deploy_dockerhub.sh || travis_terminate 1;
  - test “$TRAVIS_BRANCH” = “master” && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/backend_deploy_heroku.sh;


